#include "pch.h"
#include "Key.h"

Key::Key() 
{ }

Key::Key(SDL_Scancode scancode) : code(Code::Unknown)
{
    auto it = scancodeMap.find(scancode);

    if (it != scancodeMap.end())
    {
        code = it->second;
    }
}

bool Key::operator==(const Key& other) const
{
    return code == other.code;
}

const std::unordered_map<SDL_Scancode, Key::Code> Key::scancodeMap =
{
    {SDL_SCANCODE_A, Key::Code::A},
    {SDL_SCANCODE_B, Key::Code::B},
    {SDL_SCANCODE_C, Key::Code::C},
    {SDL_SCANCODE_D, Key::Code::D},
    {SDL_SCANCODE_E, Key::Code::E},
    {SDL_SCANCODE_F, Key::Code::F},
    {SDL_SCANCODE_G, Key::Code::G},
    {SDL_SCANCODE_H, Key::Code::H},
    {SDL_SCANCODE_I, Key::Code::I},
    {SDL_SCANCODE_J, Key::Code::J},
    {SDL_SCANCODE_K, Key::Code::K},
    {SDL_SCANCODE_L, Key::Code::L},
    {SDL_SCANCODE_M, Key::Code::M},
    {SDL_SCANCODE_N, Key::Code::N},
    {SDL_SCANCODE_O, Key::Code::O},
    {SDL_SCANCODE_P, Key::Code::P},
    {SDL_SCANCODE_Q, Key::Code::Q},
    {SDL_SCANCODE_R, Key::Code::R},
    {SDL_SCANCODE_S, Key::Code::S},
    {SDL_SCANCODE_T, Key::Code::T},
    {SDL_SCANCODE_U, Key::Code::U},
    {SDL_SCANCODE_V, Key::Code::V},
    {SDL_SCANCODE_W, Key::Code::W},
    {SDL_SCANCODE_X, Key::Code::X},
    {SDL_SCANCODE_Y, Key::Code::Y},
    {SDL_SCANCODE_Z, Key::Code::Z},
    {SDL_SCANCODE_LCTRL, Key::Code::LCtrl},
    {SDL_SCANCODE_LSHIFT, Key::Code::LShift},
    {SDL_SCANCODE_LALT, Key::Code::LAlt},
    {SDL_SCANCODE_LGUI, Key::Code::LGUI},
    {SDL_SCANCODE_RCTRL, Key::Code::RCtrl},
    {SDL_SCANCODE_RSHIFT, Key::Code::RShift},
    {SDL_SCANCODE_RALT, Key::Code::RAlt},
    {SDL_SCANCODE_RGUI, Key::Code::RGUI},
    {SDL_SCANCODE_1, Key::Code::Num1},
    {SDL_SCANCODE_2, Key::Code::Num2},
    {SDL_SCANCODE_3, Key::Code::Num3},
    {SDL_SCANCODE_4, Key::Code::Num4},
    {SDL_SCANCODE_5, Key::Code::Num5},
    {SDL_SCANCODE_6, Key::Code::Num6},
    {SDL_SCANCODE_7, Key::Code::Num7},
    {SDL_SCANCODE_8, Key::Code::Num8},
    {SDL_SCANCODE_9, Key::Code::Num9},
    {SDL_SCANCODE_0, Key::Code::Num0},
    {SDL_SCANCODE_RETURN, Key::Code::Return},
    {SDL_SCANCODE_ESCAPE, Key::Code::Escape},
    {SDL_SCANCODE_BACKSPACE, Key::Code::Backspace},
    {SDL_SCANCODE_TAB, Key::Code::Tab},
    {SDL_SCANCODE_SPACE, Key::Code::Space},
    {SDL_SCANCODE_MINUS, Key::Code::Minus},
    {SDL_SCANCODE_EQUALS, Key::Code::Equals},
    {SDL_SCANCODE_LEFTBRACKET, Key::Code::LeftBracket},
    {SDL_SCANCODE_RIGHTBRACKET, Key::Code::RightBracket},
    {SDL_SCANCODE_BACKSLASH, Key::Code::Backslash},
    {SDL_SCANCODE_NONUSHASH, Key::Code::NonUSHash},
    {SDL_SCANCODE_SEMICOLON, Key::Code::Semicolon},
    {SDL_SCANCODE_APOSTROPHE, Key::Code::Apostrophe},
    {SDL_SCANCODE_GRAVE, Key::Code::Grave},
    {SDL_SCANCODE_COMMA, Key::Code::Comma},
    {SDL_SCANCODE_PERIOD, Key::Code::Period},
    {SDL_SCANCODE_SLASH, Key::Code::Slash},
    {SDL_SCANCODE_CAPSLOCK, Key::Code::CapsLock},
    {SDL_SCANCODE_F1, Key::Code::F1},
    {SDL_SCANCODE_F2, Key::Code::F2},
    {SDL_SCANCODE_F3, Key::Code::F3},
    {SDL_SCANCODE_F4, Key::Code::F4},
    {SDL_SCANCODE_F5, Key::Code::F5},
    {SDL_SCANCODE_F6, Key::Code::F6},
    {SDL_SCANCODE_F7, Key::Code::F7},
    {SDL_SCANCODE_F8, Key::Code::F8},
    {SDL_SCANCODE_F9, Key::Code::F9},
    {SDL_SCANCODE_F10, Key::Code::F10},
    {SDL_SCANCODE_F11, Key::Code::F11},
    {SDL_SCANCODE_F12, Key::Code::F12},
    {SDL_SCANCODE_F13, Key::Code::F13},
    {SDL_SCANCODE_F14, Key::Code::F14},
    {SDL_SCANCODE_F15, Key::Code::F15},
    {SDL_SCANCODE_F16, Key::Code::F16},
    {SDL_SCANCODE_F17, Key::Code::F17},
    {SDL_SCANCODE_F18, Key::Code::F18},
    {SDL_SCANCODE_F19, Key::Code::F19},
    {SDL_SCANCODE_F20, Key::Code::F20},
    {SDL_SCANCODE_F21, Key::Code::F21},
    {SDL_SCANCODE_F22, Key::Code::F22},
    {SDL_SCANCODE_F23, Key::Code::F23},
    {SDL_SCANCODE_F24, Key::Code::F24},
    {SDL_SCANCODE_PRINTSCREEN, Key::Code::PrintScreen},
    {SDL_SCANCODE_SCROLLLOCK, Key::Code::ScrollLock},
    {SDL_SCANCODE_PAUSE, Key::Code::Pause},
    {SDL_SCANCODE_INSERT, Key::Code::Insert},
    {SDL_SCANCODE_HOME, Key::Code::Home},
    {SDL_SCANCODE_PAGEUP, Key::Code::PageUp},
    {SDL_SCANCODE_DELETE, Key::Code::Delete},
    {SDL_SCANCODE_END, Key::Code::End},
    {SDL_SCANCODE_PAGEDOWN, Key::Code::PageDown},
    {SDL_SCANCODE_RIGHT, Key::Code::Right},
    {SDL_SCANCODE_LEFT, Key::Code::Left},
    {SDL_SCANCODE_DOWN, Key::Code::Down},
    {SDL_SCANCODE_UP, Key::Code::Up},
    {SDL_SCANCODE_NUMLOCKCLEAR, Key::Code::NumLockClear},
    {SDL_SCANCODE_KP_DIVIDE, Key::Code::KeypadDivide},
    {SDL_SCANCODE_KP_MULTIPLY, Key::Code::KeypadMultiply},
    {SDL_SCANCODE_KP_MINUS, Key::Code::KeypadMinus},
    {SDL_SCANCODE_KP_PLUS, Key::Code::KeypadPlus},
    {SDL_SCANCODE_KP_ENTER, Key::Code::KeypadEnter},
    {SDL_SCANCODE_KP_1, Key::Code::Keypad1},
    {SDL_SCANCODE_KP_2, Key::Code::Keypad2},
    {SDL_SCANCODE_KP_3, Key::Code::Keypad3},
    {SDL_SCANCODE_KP_4, Key::Code::Keypad4},
    {SDL_SCANCODE_KP_5, Key::Code::Keypad5},
    {SDL_SCANCODE_KP_6, Key::Code::Keypad6},
    {SDL_SCANCODE_KP_7, Key::Code::Keypad7},
    {SDL_SCANCODE_KP_8, Key::Code::Keypad8},
    {SDL_SCANCODE_KP_9, Key::Code::Keypad9},
    {SDL_SCANCODE_KP_0, Key::Code::Keypad0},
    {SDL_SCANCODE_KP_PERIOD, Key::Code::KeypadPeriod},
    {SDL_SCANCODE_KP_PLUSMINUS, Key::Code::KeypadPlusMinus},
    {SDL_SCANCODE_KP_CLEAR, Key::Code::KeypadClear},
    {SDL_SCANCODE_KP_CLEARENTRY, Key::Code::KeypadClearEntry},
    {SDL_SCANCODE_KP_BINARY, Key::Code::KeypadBinary},
    {SDL_SCANCODE_KP_OCTAL, Key::Code::KeypadOctal},
    {SDL_SCANCODE_KP_DECIMAL, Key::Code::KeypadDecimal},
    {SDL_SCANCODE_KP_HEXADECIMAL, Key::Code::KeypadHexadecimal},
    {SDL_SCANCODE_LCTRL, Key::Code::LCtrl},
    {SDL_SCANCODE_LSHIFT, Key::Code::LShift},
    {SDL_SCANCODE_LALT, Key::Code::LAlt},
    {SDL_SCANCODE_LGUI, Key::Code::LGUI},
    {SDL_SCANCODE_RCTRL, Key::Code::RCtrl},
    {SDL_SCANCODE_RSHIFT, Key::Code::RShift},
    {SDL_SCANCODE_RALT, Key::Code::RAlt},
    {SDL_SCANCODE_RGUI, Key::Code::RGUI},
    {SDL_SCANCODE_MODE, Key::Code::Mode}
};